language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
install:
  - pip install -r requirements/dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then python setup.py check --metadata --restructuredtext --strict; fi
  - ./run_tests.py
